[project]
name = "cloba-tableextracter"
version = "0.1.0"
description = "Extract table with cloba OCR and save as .csv"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "auto-py-to-exe>=2.46.0",
    "pypdf>=5.5.0",
]
